/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShoppingListRouteImport } from './routes/shopping-list'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InventoryIndexRouteImport } from './routes/inventory.index'
import { Route as InventoryItemIdRouteImport } from './routes/inventory.$itemId'

const ShoppingListRoute = ShoppingListRouteImport.update({
  id: '/shopping-list',
  path: '/shopping-list',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InventoryRoute,
} as any)
const InventoryItemIdRoute = InventoryItemIdRouteImport.update({
  id: '/$itemId',
  path: '/$itemId',
  getParentRoute: () => InventoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/shopping-list': typeof ShoppingListRoute
  '/inventory/$itemId': typeof InventoryItemIdRoute
  '/inventory/': typeof InventoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/shopping-list': typeof ShoppingListRoute
  '/inventory/$itemId': typeof InventoryItemIdRoute
  '/inventory': typeof InventoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/shopping-list': typeof ShoppingListRoute
  '/inventory/$itemId': typeof InventoryItemIdRoute
  '/inventory/': typeof InventoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/inventory'
    | '/reset-password'
    | '/settings'
    | '/shopping-list'
    | '/inventory/$itemId'
    | '/inventory/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/settings'
    | '/shopping-list'
    | '/inventory/$itemId'
    | '/inventory'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/inventory'
    | '/reset-password'
    | '/settings'
    | '/shopping-list'
    | '/inventory/$itemId'
    | '/inventory/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InventoryRoute: typeof InventoryRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  ShoppingListRoute: typeof ShoppingListRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shopping-list': {
      id: '/shopping-list'
      path: '/shopping-list'
      fullPath: '/shopping-list'
      preLoaderRoute: typeof ShoppingListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/inventory/$itemId': {
      id: '/inventory/$itemId'
      path: '/$itemId'
      fullPath: '/inventory/$itemId'
      preLoaderRoute: typeof InventoryItemIdRouteImport
      parentRoute: typeof InventoryRoute
    }
  }
}

interface InventoryRouteChildren {
  InventoryItemIdRoute: typeof InventoryItemIdRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
}

const InventoryRouteChildren: InventoryRouteChildren = {
  InventoryItemIdRoute: InventoryItemIdRoute,
  InventoryIndexRoute: InventoryIndexRoute,
}

const InventoryRouteWithChildren = InventoryRoute._addFileChildren(
  InventoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InventoryRoute: InventoryRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  ShoppingListRoute: ShoppingListRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
